### ISSUE TITLE
Falha ao obter resultados em XML

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/search-journals#439]
URL: https://search.scielo.org/index.php?output=xml&site=scielo&col=org&q=%28%28sponsor%3A%28fapesp%29%29%29+OR+%28sponsor%3A%28Funda%C3%A7%C3%A3o+de+Amparo+a+Pesquisa+do+Estado+de+S%C3%A3o+Paulo%29%29+OR+%28sponsor%3A%28sC3%A3o+paulo+research+foundation%29%29&count=100&from=1&page=1

Resultado:
```html
<html>

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <title>Error 500 {msg=getTransformer fails in getContentType,trace=java.lang.RuntimeException: getTransformer fails in getContentType at org.apache.solr.response.XSLTResponseWriter.getContentType(XSLTResponseWriter.java:74) at
    org.apache.solr.servlet.HttpSolrCall.writeResponse(HttpSolrCall.java:715) at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:469) at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:257) at
    org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:208) at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) at
    org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577) at
    org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) at
    org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215) at
    org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110) at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) at org.eclipse.jetty.server.Server.handle(Server.java:499) at
    org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) at
    org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) at java.lang.Thread.run(Thread.java:748)Caused by: java.io.IOException: Unable to
    initialize Templates &apos;export-xml.xsl&apos; at org.apache.solr.util.xslt.TransformerProvider.getTemplates(TransformerProvider.java:119) at org.apache.solr.util.xslt.TransformerProvider.getTransformer(TransformerProvider.java:81) at
    org.apache.solr.response.XSLTResponseWriter.getTransformer(XSLTResponseWriter.java:131) at org.apache.solr.response.XSLTResponseWriter.getContentType(XSLTResponseWriter.java:71) ... 24 moreCaused by:
    org.apache.solr.core.SolrResourceNotFoundException: Can&apos;t find resource &apos;xslt/export-xml.xsl&apos; in classpath or &apos;/opt/solr/server/solr/mycores/articles&apos; at
    org.apache.solr.core.SolrResourceLoader.openResource(SolrResourceLoader.java:408) at org.apache.solr.util.xslt.TransformerProvider.getTemplates(TransformerProvider.java:109) ... 27 more,code=500}</title>
</head>

<body>
  <h2>HTTP ERROR 500</h2>
  <p>Problem accessing /solr/articles/select/. Reason:
    <pre>    {msg=getTransformer fails in getContentType,trace=java.lang.RuntimeException: getTransformer fails in getContentType	at org.apache.solr.response.XSLTResponseWriter.getContentType(XSLTResponseWriter.java:74)	at org.apache.solr.servlet.HttpSolrCall.writeResponse(HttpSolrCall.java:715)	at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:469)	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:257)	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:208)	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)	at org.eclipse.jetty.server.Server.handle(Server.java:499)	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)	at java.lang.Thread.run(Thread.java:748)Caused by: java.io.IOException: Unable to initialize Templates &apos;export-xml.xsl&apos;	at org.apache.solr.util.xslt.TransformerProvider.getTemplates(TransformerProvider.java:119)	at org.apache.solr.util.xslt.TransformerProvider.getTransformer(TransformerProvider.java:81)	at org.apache.solr.response.XSLTResponseWriter.getTransformer(XSLTResponseWriter.java:131)	at org.apache.solr.response.XSLTResponseWriter.getContentType(XSLTResponseWriter.java:71)	... 24 moreCaused by: org.apache.solr.core.SolrResourceNotFoundException: Can&apos;t find resource &apos;xslt/export-xml.xsl&apos; in classpath or &apos;/opt/solr/server/solr/mycores/articles&apos;	at org.apache.solr.core.SolrResourceLoader.openResource(SolrResourceLoader.java:408)	at org.apache.solr.util.xslt.TransformerProvider.getTemplates(TransformerProvider.java:109)	... 27 more,code=500}</pre>
  </p>
  <hr><i><small>Powered by Jetty://</small></i>
  <hr />
</body>

</html>
```

**Comment by cesarbruschetta** [comment]
Commit que solucionou o problema https://github.com/scieloorg/search-journals/commit/3ca3020548211d23cf1abbc28a6095ddf11707e4
